### ISSUE TITLE
Faulty estimates for more than one battery (at least on Linux)

### ISSUE THREAD

**Issue by meepoSenpai** [Kentzo/Power#10]
The problem here is, that if more than one battery is available, the estimated remaining time for the battery that currently isn't in use isn't considered at all.

It's basically the same as the `acpi` sample-output in the attached screenshot, just that the output of power is in minutes.
![2016-06-08-023936_475x45_scrot](https://cloud.githubusercontent.com/assets/5368224/15879216/60c30e78-2d22-11e6-86fd-43bd76cc74ce.png)

**Comment by Kentzo** [comment]
@meepoSenpai Which OS is it?

**Comment by Kentzo** [comment]
It should be considered: https://github.com/Kentzo/Power/blob/master/power/linux.py#L144-L175

**Comment by meepoSenpai** [comment]
![2016-06-08-025156_711x242_scrot](https://cloud.githubusercontent.com/assets/5368224/15879504/11932006-2d25-11e6-8db5-f4eefa0a5329.png)
This is to show, that the output does not really differ from the `acpi` output, except for the time unit.

And here is the output of the added print.
![2016-06-08-025921_597x112_scrot](https://cloud.githubusercontent.com/assets/5368224/15879560/7cdfff0a-2d25-11e6-9b93-4481f8a55e5b.png)

It seems to just recognize one of the batteries for some reason

**Comment by meepoSenpai** [comment]
Okay. I found the source of the error.

Since only discharging batteries are measured, and the battery that isn't currently in use isn't recognized as discharging (which it effectivley isn't) it is ignored in calculating the rest of the time.

**Comment by Kentzo** [comment]
Do you mean it's not listed in `/sys/class/power_supply` ?

**Comment by meepoSenpai** [comment]
No. I meant that the battery simply isn't marked as discharging. But I guess I have found a solution to the problem. I'll make a pull request so you can simply review what I did (:
