### ISSUE TITLE
Problem importing module in macOS 10.13.3

### ISSUE THREAD

**Issue by tinoargentino** [Kentzo/Power#32]
Hi! I installed the module today, v1.4 but when I try to import it I'm getting the following error:

import power
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/valentinschmidt/anaconda3/lib/python3.6/site-packages/power/__init__.py", line 28, in <module>
    from power.darwin import PowerManagement
  File "/Users/valentinschmidt/anaconda3/lib/python3.6/site-packages/power/darwin.py", line 163, in <module>
    class PowerSourcesNotificationsObserver(NSObject):
objc.BadPrototypeError: **Objective-C expects 1 arguments, Python argument has 2 arguments** for <unbound selector addObserver of PowerSourcesNotificationsObserver at 0x107273370>

Can someone help me please?

**Comment by Kentzo** [comment]
Hmm perhaps underlying C-API changed. I'll take a look.

**Comment by rickyzhang82** [comment]
Any update?

**Comment by TomFaulkner** [comment]
Any progress on this?

**Comment by timpelser** [comment]
Has this been resolved yet?

**Comment by proftc** [comment]
Has anyone solved this yet? It would be useful to have this working

**Comment by Kentzo** [comment]
I suspect the underlying definitions have changed. Should be easy to test by [re-generating](https://github.com/Kentzo/Power/blob/2c99b156546225e448f7030681af3df5cd345e4b/power/darwin.py#L16) metadata.

**Comment by Kentzo** [comment]
Fixed in the `develop` branch.

**Comment by proftc** [comment]
Great I'll give it a try
