### ISSUE TITLE
Unable to find energy_now file on Linux

### ISSUE THREAD

**Issue by justbuchanan** [Kentzo/Power#8]
Hi, I've tried using this module on my Linux system with kernel version 4.1.6 and it hits a `FileNotFoundError` because the `energy_now` file doesn't exist for my battery.  I do see a file in there called `charge_now` though.  Do you know if this is due to a renaming in more recent kernel versions?  If so, would you be interested in a pull-request that fixes this?  Thanks!

**Comment by Kentzo** [comment]
Looks like it is.

Fortunately it is just rename, content seems to be the same.

Best Regards
Ilya Kulakov

**Comment by justbuchanan** [comment]
Ok cool.  Do you plan on fixing this sometime and/or would you like me to submit a pull request?

**Comment by Kentzo** [comment]
First of all I need to fix the behavior: it should fallback to default implementation in cases like that.

Best Regards
Ilya Kulakov

**Comment by kootenpv** [comment]
2 years later still not fixed right?

**Comment by Kentzo** [comment]
No, but thank you for bringing my attention.

**Comment by Kentzo** [comment]
Should be fixed in the develop branch.
